### PR TITLE
Add additional content to Cryptocurrency Bill

### LINKED ISSUE #5: Iterate and Add to Model Legislation for Regulating Cryptocurrency
As a Crypto fan I want [Model Legislation on Regulation of Cryptocurrencies](https://github.com/TurqCo/turqV1/blob/master/Cryptocurrencies%20Are%20Currency%20Model%20Bill.md) to be built out more and further defined so that it stands a chance of making its way through a legislative body.

### PR DESCRIPTION
**Pull request by acolytec3**
Fixes #5 

Updates:
- Added some additional language defining digital tokens in Section 2.2
- Added additional subprovisions under 4.1 to expand specific rules around taxation 
- Folded the original 5.2 into a subsection of 5.1
- Added a new 5.2 that excludes cryptocurrencies with a single majority owner from the provisions of the bill

### CODE REVIEW

**Comment by acolytec3** [comment]
This is just a first pass.  Is this the kind of content you were thinking?  Are there specific additional areas you want addressed or were thinking about?

**Comment by TurqCo** [comment]
Yes, this is the type of thing I had in mind.

I'm trying not to be too specific because the goal is definitely to see where this can go with little direction.

**Comment by TurqCo** [comment]
Didn't mean to close out the issue, given you said that was a first pass. My apologies.

I think what you're adding is looking great.

**Comment by acolytec3** [comment]
Hmm, ok, I guess I'm struggling to think of what else to add so any additional thoughts on areas to expand (or ideas for additional provisions) would be helpful. The biggest concerns I have around crypto from a regulatory perspective is really keyed around taxation and the possibility for joe schmoes like me to get caught up in complicated tax nonsense when I'm not using it as an investment platform but just transacting in my daily business and I think I've largely covered that in what I've put in there already.

**Comment by TurqCo** [comment]
If you want to stick with what's here, that's 100% cool with me.

If you want a few rabbit holes to possibly jump down, then perhaps some potential areas to explore would be:
1) When you say "all cryptocurrencies" does that mean there is no differentiation between utility tokens vs security tokens? If there is a difference, how should that be handled?
2) Would there be a difference between how LLC's/S Corps are taxed (since most of their funds passthrough to the individuals who own them) vs how C Corps are taxed on income & payroll?
2) Do smart contracts have to be considered in any capacity?

**Comment by acolytec3** [comment]
Hmm, let me think on #2.  I think I address your first question in the special exceptions in Section 5 where I explicitly exclude tokens that could be deemed securities (as defined in section 2).

As far as smart contracts, I think I could add another exclusion to keep them out of it since that's really an application/entity type question rather than the token or currency itself.  Let me noodle on it the next day or two and see what else I've got.

**Comment by TurqCo** [comment]
Sounds great!!

**Pull request merged**
